//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int Reference_Number { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date_of_Journey { get; set; }
        public Nullable<int> Flight_Id { get; set; }
        public string Flight_Name { get; set; }
        public string Seat_Number { get; set; }
    }
}
