//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSeatDetil
    {
        public int Id { get; set; }
        public string FlightName { get; set; }
        public Nullable<int> FlightNumber { get; set; }
        public string FlightDate { get; set; }
        public string SeatNumber { get; set; }
    }
}
