//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Details
    {
        public int Id { get; set; }
        public string Flight_Name { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Arrival_Time { get; set; }
        public string Departure_Time { get; set; }
        public string Flight_Class { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Seats { get; set; }
    }
}
